---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kindle-converter-ingress
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: kindle.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kindle-converter
                port:
                  number: 80
