---
apiVersion: v1
kind: Secret
metadata:
  name: kindle-smtp
  namespace: media
type: Opaque
stringData:
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_USER: "donaldweeksiii@gmail.com"
  SMTP_PASS: "rhqj fpit gmbb fbfz"
  SMTP_SENDER: "donaldweeksiii@gmail.com"
