---
apiVersion: v1
kind: Secret
metadata:
  name: kindle-smtp
  namespace: media
type: Opaque
stringData:
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_USER: "YOUR_EMAIL@gmail.com"
  SMTP_PASS: "YOUR_APP_PASSWORD"
  SMTP_SENDER: "YOUR_EMAIL@gmail.com"
